---
- hosts: all
  become: yes
  tasks: 
  - name: install web server on ubuntu ansible nodes
    apt:
      name: apache2
      state: present
    when: anisble_os_family =="Debian"

  - name: start web server 
    service:
      name: apache2
      state: started
    when: anisble_os_family =="Debian"
